### ISSUE TITLE
libre2.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ewen-lbh** [intersimone999/pyqtws#10]
I'm running Arch Linux, and first tried installing through the AUR, then by cloning the repo and installing dependencies as described in the README, but both methods give this error: when running `silo --help` (or `./silo --help`)

```python
Traceback (most recent call last):
  File "/home/ewen/.buildarea/pyqtws/pyqtws/main.py", line 11, in <module>
    from mainwindow import QTWSMainWindow
  File "/home/ewen/.buildarea/pyqtws/pyqtws/mainwindow.py", line 5, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineProfile, QWebEngineFullScreenRequest
ImportError: libre2.so.8: cannot open shared object file: No such file or directory
```

**Comment by intersimone999** [comment]
A system update  will most likely fix that. The file `/usr/lib/libre2.so.8` in my system is owned by the package `re2` version `1:20200801-1` (Arch Linux as well). Maybe you can try to update that package.

**Comment by ewen-lbh** [comment]
@intersimone999 yeah didn't even think about that before opening an issue, sorry... "Always `yay` before asking" I guess...

Will get back once I update and try again.
