### ISSUE TITLE
Can't make audio\video calls in Skype

### ISSUE THREAD

**Issue by exelents** [intersimone999/pyqtws#5]
Hello,
When I run a skype in your app, I have all call buttons disabled, so I can't call, only chat. Can you do something with it?

**Comment by intersimone999** [comment]
I guess this is a problem with the QtWebEngine component we use to render the web pages: I tried Falkon and it doesn't work on it either. Probably, the only thing we can do is wait for an update on their side.

**Comment by exelents** [comment]
That's a pity :(
