### ISSUE TITLE
HIDPI

### ISSUE THREAD

**Issue by exelents** [intersimone999/pyqtws#6]
I would afford one more question. I have HIDPI screen on my notebook. How can I use your app with elements not to be so small? I have 
       xrandr --dpi 157 &
in my .xprofile config, and HIDPI scheme in GTK3, but for your app it doesn't help.

**Comment by intersimone999** [comment]
You can try running silo like this, for example:
```
QT_AUTO_SCREEN_SCALE_FACTOR=1 silo -a {appName}
```
Could you please check if it works? If it does, I will update the desktop files as well, so that everything is completely automated.

**Comment by exelents** [comment]
Unfortunately, it doesn't work, even if i change value from 1 to, for example, 2 or 3. Also, now whatsapp web app ask me "to update chrome".

**Comment by exelents** [comment]
for me, this 
QT_SCALE_FACTOR=1.58 silo -a whatsapp
gonna work. So I manually set scale factor.

**Comment by intersimone999** [comment]
Great! Since the generic solution doesn't work, I guess there is no need to update the desktop files.
